import type { Metadata } from "next";
import { ubuntu } from "./ui/fonts";
import "@styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.className} grid h-svh w-svw place-items-center gap-0 bg-green-200 text-left text-lg antialiased md:h-screen md:w-full`}
      >
        <main className="grid h-svh w-svw place-items-center px-4 md:max-w-[90rem] md:px-10">
          {children}
        </main>
      </body>
    </html>
  );
}
